### ISSUE TITLE
IOS Bug: border of my component cropped in first render

### ISSUE THREAD

**Issue by rully-saputra15** [callstack/react-native-pager-view#523]
## Environment
react native: https://github.com/expo/react-native/archive/sdk-44.0.0.tar.gz
react: 17
expo: 44
pager-view: 3.5.9

## Description

Hello guys, I have a problem with the look of the pager view. For the first render, the component border inside pager view was cropped and after I did slide, the component look good and nothing happen. Is anyone have the same problem as me? the component that I used from the native-base library

**Comment by crosswin-ecgroup** [comment]
I'm also facing the same issue. @rully-saputra15 , Did you fix this issue?

**Comment by monahans** [comment]
I also have this issue. It seems to add a margin to the bottom of the view but then it disappears once you start swiping to the next screen

**Comment by crosswin-ecgroup** [comment]
> I also have this issue. It seems to add a margin to the bottom of the view but then it disappears once you start swiping to the next screen
@monahans 
Yes, I face the same issue. I fixed it by reverting to the old version.

**Comment by monahans** [comment]
@crosswin-ecgroup thanks! Which version did you revert to?

**Comment by crosswin-ecgroup** [comment]
Use this @monahans 
"react-native-pager-view": "5.4.11",

**Comment by JstnEdr** [comment]
This had me stumped for an entire day before I narrowed it down to react-native-pager-view. Can confirm that rolling back to `5.4.11` solved the issue

**Comment by crosswin-ecgroup** [comment]
Yes its worked for me @JstnEdr

**Comment by andreialecu** [comment]
Ran into the same issue and I did some investigation on this today. `5.4.13` is the last good version, on `5.4.14` this bug starts occuring.

There is only one commit:
https://github.com/callstack/react-native-pager-view/compare/v5.4.13...v5.4.14

This seems to be caused by this early return:
![image](https://user-images.githubusercontent.com/697707/168995647-356fcb09-7001-4216-a47c-4bad9d943bf3.png)

I reverted that change and the issue was fixed.

/cc @danilobuerger

**Comment by codeion** [comment]
This issue is still happening with latest version (v5.4.24) on iOS 14.8

**Comment by tunnaduong** [comment]
I don't know why but when I downgrade it to 5.4.13 or the previous version, that bug still exists. Any detailed step by steps tutorial on how to downgrade an npm package?

For me:
```
1. Change the version in package.json
2. Run "npm install react-native-pager-view@5.4.13"
3. Pray for the hope that it will work but it's not :)

```
Is that it?

**Comment by quietones** [comment]
I'm also experiencing this issue still on v5.4.24.

I suggest this should be re-opened.

**Comment by codeion** [comment]
Depending on your use case, try with style overflow: 'visible'

**Comment by tunnaduong** [comment]
I confirmed guys that downgrading Expo to version 44 solved the problem!
