### ISSUE TITLE
App is getting crashed when switching the navigator, java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true

### ISSUE THREAD

**Issue by rifad4u** [callstack/react-native-pager-view#859]
## Environment

"@react-navigation/material-top-tabs": "^6.6.14",
"@react-navigation/native": "^6.1.18",
"@react-navigation/native-stack": "^6.11.0",
"react": "18.3.1",
"react-native": "0.75.2",
"react-native-pager-view": "^6.3.4",
"react-native-safe-area-context": "^4.10.9",
"react-native-screens": "^3.34.0",
"react-native-tab-view": "^3.5.2"

## Description

I have a tab navigator in a post login stack screen, one of the tabs visibility is based on a value of state variable. so when i do logout first i'm setting the value of the state variable to false, then i'm switching the stack to pre login stack. at this time app is getting crashed

Getting logs in Android studio like below
java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{7d03f4b VFED..... .......D 0,0-1080,1736 #2}, adapter:com.reactnativepagerview.ViewPagerAdapter@5f5fd28, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@1cf2a41, context:com.facebook.react.uimanager.ThemedReactContext@c1e63c

## Reproducible Demo

https://github.com/rifad4u/pagerviewcrash.git

**Comment by jingp-ofload** [comment]
/+ 1

**Comment by rifad4u** [comment]
@MrRefactor @yilinjuang  @WoLewicki  @okwasniewski  @szymonrybczak @szydlovsky  any update on this issue?

**Comment by troZee** [comment]
Hi @rifad4u

Just a quick reminder to please avoid pinging other contributors unnecessarily. Let's ensure we're not disturbing others unless it's critical to the discussion. Thanks for your understanding and cooperation! PRs and other investigations are welcome 🙏 

Best regards,
Piotr Trocki

**Comment by troZee** [comment]
@kamill90

**Comment by ShaoGongBra** [comment]
The same problem

**Comment by sankar-gp** [comment]
Any update on this issue?

**Comment by sankar-gp** [comment]
Im facing this issue on react native 0.75.4 with "react-native-pager-view": "^6.4.1",

**Comment by LinhLM23496** [comment]
+ 1

**Comment by MrRefactor** [comment]
Looking into this

**Comment by hengkx** [comment]
enabled new arch. same error

**Comment by troZee** [comment]
Similar issue: https://github.com/callstack/react-native-pager-view/issues/891#issuecomment-2447236943

**Comment by gstaykov** [comment]
> enabled new arch. same error

When new arch type is disabled error is resolved.

**Comment by Doom2layer** [comment]
Any update? I just saw this package and I installed it in my RN app that uses version 0.76,
after I implemented the PagerView whenever I try to use anything related to navigation the app crashes.

**Comment by pankaj610** [comment]
Getting the same issue in RN 0.73.9, do we have any update?

**Comment by MrRefactor** [comment]
As I messaged previously, looking into that issue. Feel free to contribute and open PR.

**Comment by jingp-ofload** [comment]
I got this because I was following the example with reanimated library, I don't have this error after I get rid of reanimated from react-native-pager-view.

**Comment by duongnguyen17** [comment]
Getting the same issue in RN 0.76.1 when newArchEnabled=true, do we have any update?

**Comment by abhayagrawal-fareye** [comment]
I am facing same issue on react-native 0.76.1 and react-native-pagerview - 6.5.0

**Comment by NetPumi2** [comment]
+1

**Comment by pankaj610** [comment]
> Getting the same issue in RN 0.76.1 when newArchEnabled=true, do we have any update?

I am even getting this issue when newArchEnabled=false

**Comment by mlukasik-dev** [comment]
+1 on new arch with expo 52

**Comment by radko93** [comment]
@MrRefactor this issue is back in 6.6.0 on Fabric, probably due to #929

**Comment by MrRefactor** [comment]
> [@MrRefactor](https://github.com/MrRefactor) this issue is back in 6.6.0 on Fabric, probably due to [#929](https://github.com/callstack/react-native-pager-view/pull/929)

checking

**Comment by MrRefactor** [comment]
https://github.com/callstack/react-native-pager-view/releases/tag/v6.6.1 @radko93

**Comment by fendyk** [comment]
This error / crash still occurs when you do:

```pageMargin={24}```

**Comment by DGVIP** [comment]
This issue still happens in version 6.7.0 using react native 0.76.7 with Fabric

**Comment by iliapnmrv** [comment]
Hi! I'm also having this issue. with Fabric
```json
"react-native": "0.77.1",
"react-native-pager-view": "6.7.0",
```

**Comment by JoniVR** [comment]
Just an fyi, we have seen 0 cases of this error happening since applying the patch from #970 (with about 5k users), so if you're still running into this, you can always try patching `react-native-pager-view` until a proper fix is released.

**Comment by dokienkkk** [comment]
> Just an fyi, we have seen 0 cases of this error happening since applying the patch from [#970](https://github.com/callstack/react-native-pager-view/pull/970) (with about 5k users), so if you're still running into this, you can always try patching `react-native-pager-view` until a proper fix is released.
> 
> I do think this issue should probably be reopened as it's obvious that this is still happening.

Thank you for your fix, but after I apply this patch, `setPage` is not working (page doesn't change at all). `setPageWithoutAnimation` is working fine. I'm using RN 0.76.6

**Comment by iliapnmrv** [comment]
Hi! I've tried to apply a patch from https://github.com/callstack/react-native-pager-view/pull/970
Some users complain on not working `jumpTo` method from `react-native-tab-view`. Unfortunately I'm unable to reproduce it for now
RN 0.78.1, New architecture

**Comment by alissonph** [comment]
I'm still facing this issue. I can see on Crashlytics the same crash happening.

react-native-pager-view 6.8.1
react-native 0.78.2 (new architecture enabled)

**Comment by CostasCF** [comment]
any solutions?

**Comment by MrRefactor** [comment]
Hey everyone, I have implemented a fix in this https://github.com/callstack/react-native-pager-view/pull/1063 - please validate it if your crashes are resolved. Once I will finish testing it I will cut a new version.

**Comment by azr-arch** [comment]
facing same issue

**Comment by SamarthKadam** [comment]
Did anybody try @MrRefactor changes?

**Comment by azr-arch** [comment]
still facing this issue 
```
 FATAL EXCEPTION: main
 Process: com.myapp, PID: 30018
 java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{e2e5b6b VFED..... ......ID 0,0-1080,1179 #c}, adapter:com.reactnativepagerview.ViewPagerAdapter@2c25760, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@959b6c8, context:com.facebook.react.uimanager.ThemedReactContext@7d08b94
```
    "react": "19.1.1",
    "react-native": "0.82.0",
    "react-native-pager-view": "8.0.0",

**Comment by azr-arch** [comment]
@MrRefactor  sir , can you please look into this ?

**Comment by azr-arch** [comment]
> Did anybody try [@MrRefactor](https://github.com/MrRefactor) changes?

i tried its working on development build.
but crashing on release build
```
 dispatchMountItems: caught exception, displaying mount state
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLayoutDirection()' on a null object reference
``` 
device: redmi note 9 - android 12

**Comment by MrRefactor** [comment]
@azr-arch adjusted the PR, please recheck

**Comment by azr-arch** [comment]
@MrRefactor  
no luck sir!

```
 dispatchMountItems: caught exception, displaying mount state
                                                 java.lang.NullPointerException: Attempt to invoke virtual method 'int android.view.View.getLayoutDirection()' on a null object reference
```


the crash above has been fixed in the release build.  


however, our core crash remains unresolved
```
FATAL EXCEPTION: main
                                                 Process: com.my.app, PID: 9094
                                                 java.lang.IllegalArgumentException: Scrapped or attached views may not be recycled. isScrap:false isAttached:true androidx.viewpager2.widget.ViewPager2$RecyclerViewImpl{9f72ad8 VFED..... ......ID 0,0-1080,1133 #8}, adapter:com.reactnativepagerview.ViewPagerAdapter@262a452, layout:androidx.viewpager2.widget.ViewPager2$LinearLayoutManagerImpl@85b3e31, context:com.facebook.react.uimanager.ThemedReactContext@8a049a
                                                 	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleViewHolderInternal(RecyclerView.java:7071)
                                                 	at androidx.recyclerview.widget.RecyclerView$Recycler.recycleView(RecyclerView.java:7007)
                                                 	at androidx.recyclerview.widget.RecyclerView$LayoutManager.removeAndRecycleViewAt(RecyclerView.java:9741)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.recycleChildren(LinearLayoutManager.java:1468)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.recycleViewsFromEnd(LinearLayoutManager.java:1562)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.recycleByLayoutState(LinearLayoutManager.java:1587)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.fill(LinearLayoutManager.java:1613)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.scrollBy(LinearLayoutManager.java:1425)
                                                 	at androidx.recyclerview.widget.LinearLayoutManager.scrollHorizontallyBy(LinearLayoutManager.java:1145)
                                                 	at androidx.recyclerview.widget.RecyclerView.scrollStep(RecyclerView.java:2047)
                                                 	at androidx.recyclerview.widget.RecyclerView$ViewFlinger.run(RecyclerView.java:5835)
                                                 	at android.view.Choreographer$CallbackRecord.run(Choreographer.java:1160)
                                                 	at android.view.Choreographer.doCallbacks(Choreographer.java:950)
                                                 	at android.view.Choreographer.doFrame(Choreographer.java:874)
                                                 	at android.view.Choreographer$FrameDisplayEventReceiver.run(Choreographer.java:1142)
                                                 	at android.os.Handler.handleCallback(Handler.java:938)
                                                 	at android.os.Handler.dispatchMessage(Handler.java:99)
                                                 	at android.os.Looper.loopOnce(Looper.java:210)
                                                 	at android.os.Looper.loop(Looper.java:299)
                                                 	at android.app.ActivityThread.main(ActivityThread.java:8319)
                                                 	at java.lang.reflect.Method.invoke(Native Method)
                                                 	at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:556)
                                                 	at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1038)

```

**Comment by MrRefactor** [comment]
@azr-arch what are the repro steps? Could you provide repro repo?

**Comment by azr-arch** [comment]
> [@azr-arch](https://github.com/azr-arch) what are the repro steps? Could you provide repro repo?

i couldn't provide a repro repo at this, it would take time to set it up.

until then, i am attaching a video, and code structure. see if you can get something out of them

**Comment by azr-arch** [comment]
@MrRefactor 
https://github.com/user-attachments/assets/58e4b77d-e782-4210-b1d7-a9a724a5ac00


 Heres the video. 
Steps i took
- scroll a list
- press double back during scroll

**Comment by MrRefactor** [comment]
@azr-arch what are you using for the tabs component?

**Comment by azr-arch** [comment]
@MrRefactor 
Here's the simplified structure
```tsx
import { createMaterialTopTabNavigator } from '@react-navigation/material-top-tabs';
const TabNavigation = createMaterialTopTabNavigator();

function MainScreen({ route, navigation }) {
  const [activeModel, setActiveModel] = useState(null);
  const [matchingCount, setMatchingCount] = useState(0);
  
  useEffect(() => {
    // Fetch model data
    // Calculate matching items
  }, [route.params]);
  
  return (
    <>
      <HeaderComponent model={activeModel} count={matchingCount} />
      <TabNavigator.Navigator tabBar={props => <CustomTabBar {...props} /> ...>
        ...other screens
        <TabNavigation.Screen
                name="Property"
                component={PropertyListScreen}
                initialParams={{ requiredParams }}
                options={{ title: "Property" }}
              />
      </TabNavigator>
    </>
  );
}

function PropertyListScreen({ filters, onCountUpdate }) {
  const [items, setItems] = useState([]);
  
  const loadItems = () => {
    // API call with filters
    // Update count in parent
  };
  
  return (
    <FlatList
      data={items}
      CellRendererComponent={({ children, index, style, ...props }) => {
        // zIndex manipulation for overlapping cards
        const cellStyle = [style, { zIndex: items.length - index }];
        return <View style={cellStyle}>{children}</View>;
      }}
      renderItem={({ item }) => <PropertyCard item={item} />}
    />
  );
}
```

**Comment by MrRefactor** [comment]
@azr-arch please try to patch with changes from the PR again, now it should work

**Comment by azr-arch** [comment]
> [@azr-arch](https://github.com/azr-arch) please try to patch with changes from the PR again, now it should work

it didnt work, leave it for now until someone else faces same issue. 
i am going to refactor my code from the bottom.

btw, Thanks a lot for the help
